name: littoral_pipeline
channels:
  - conda-forge
  - orbingol
dependencies:
  - python==3.10.12
  - pandas
  - numpy
  - pillow
  - scikit-image
  - geemap
  - earthengine-api
  - requests
  - pip
  - ipykernel
  - simplification
  - opencv
  - arosics
  - gdal 
  - coastsat-package 
  - rasterio 
  - tqdm
  - sqlite
  - matplotlib
  - pyproj
  - shapely
  - tifffile
  - huggingface_hub
  - pyyaml
  - segmentation-models-pytorch
  - six
  - torchmetrics
  - transformers
  - wandb
  - ultralytics
  - geomdl
  - pip:
      - omnicloudmask==1.0.7
      - pytmd==2.1.9
      - aquarel
=======
  - conda-forge::opencv
  - pytorch
  - torchvision
  - tqdm
  - conda-forge::ultralytics
  - conda-forge::simplification==0.7.12
  - pip
  - pip:
    - huggingface-hub==0.25.2
    - omnicloudmask==1.0.7
    - geomdl
>>>>>>> origin/coastal_geotools
